import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer";
import Topbar from "./components/topbar";

export const metadata: Metadata = {
  title: "Techit's Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
          <div className={`w-full flex flex-col`}>
            <Topbar/>
            {children}
            <Footer/>
          </div>
      </body>
    </html>
  );
}
